apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: sandeep3414/flask-rsd:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "flaskapp.ctie4mg8o28y.us-east-1.rds.amazonaws.com"  # Replace with your RDS endpoint
        - name: DB_USER
          value: "admin"                # Replace with your DB username
        - name: DB_PASSWORD
          value: "Sandy3414"        # Replace with your DB password
        - name: DB_NAME
          value: "flaskapp"             # Replace with your DB name
